name: chatapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  firebase_storage: 12.3.7
  intl: ^0.20.1
  provider: ^6.0.0
  image_picker: ^1.1.2
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
